---

- fail:
    msg: "{{ ansible_distribution_release }} {{ ansible_distribution }}"

- name: ensure directory /var/lib/nfs-provisioner is existing
  file:
    state: directory
    path: /var/lib/nfs-provisioner

- name: ensure directory /var/lib/docker is existing
  file:
    state: directory
    path: /var/lib/docker

- name: Uninstall old versions of Docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  when: uninstall_previous_docker_versions

#install docker
- name: install apt-transport-https
  package:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: add docker repository key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main

#installation:
- name: install docker and nfs common
  package:
    name: "{{ item }}"
  with_items:
    - nfs-common
    - docker.io
    - make
    - git

# User password

- name: change default password for cca-User
  user:
    name: cca-user
#    password: "$6$j0.AUDXGrqCg$vdqZhls3rFtAbpBvHerOF9t6rJfd66XtoTLfN/J.8fjGDx1Qw1tOvuaawiUpTJAf/zfBwvuNOtix4kt5x7HNX."
#    password: "$6$rounds=656000$LP8/Lou9gUYXMx3O$Ly9YiJqVu1SAsPI6pdu5g0qxz1nMJ.MlRJg1PC32leHrpBPfuwHWE8zrVxS9qkp/PqaMMdUQcVQOjW4UN8COI."
    password: "$6$rounds=656000$8TVOMa.3fTEzp6CP$Rl6zQZjVUudwCHMQuyENVqKjpBG.OsougOriElSQCOm1C8ryqlM78aqsNUACvEq0gU9B9UWB15SzvPIQW8mYe."
